// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/verify/v1/verify_code.proto

package verifypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TYPE int32

const (
	TYPE_DEFAULT TYPE = 0 // 等同 DIGIT
	TYPE_DIGIT   TYPE = 1 // 纯数字
	TYPE_LETTER  TYPE = 2 // 纯字母
	TYPE_MIXED   TYPE = 3 // 数字 + 字母
)

// Enum value maps for TYPE.
var (
	TYPE_name = map[int32]string{
		0: "DEFAULT",
		1: "DIGIT",
		2: "LETTER",
		3: "MIXED",
	}
	TYPE_value = map[string]int32{
		"DEFAULT": 0,
		"DIGIT":   1,
		"LETTER":  2,
		"MIXED":   3,
	}
)

func (x TYPE) Enum() *TYPE {
	p := new(TYPE)
	*p = x
	return p
}

func (x TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_api_verify_v1_verify_code_proto_enumTypes[0].Descriptor()
}

func (TYPE) Type() protoreflect.EnumType {
	return &file_api_verify_v1_verify_code_proto_enumTypes[0]
}

func (x TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TYPE.Descriptor instead.
func (TYPE) EnumDescriptor() ([]byte, []int) {
	return file_api_verify_v1_verify_code_proto_rawDescGZIP(), []int{0}
}

// / 请求参数
type GetVerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        uint32                 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Type          TYPE                   `protobuf:"varint,2,opt,name=type,proto3,enum=verify.v1.TYPE" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVerifyCodeRequest) Reset() {
	*x = GetVerifyCodeRequest{}
	mi := &file_api_verify_v1_verify_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeRequest) ProtoMessage() {}

func (x *GetVerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_verify_v1_verify_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_verify_v1_verify_code_proto_rawDescGZIP(), []int{0}
}

func (x *GetVerifyCodeRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *GetVerifyCodeRequest) GetType() TYPE {
	if x != nil {
		return x.Type
	}
	return TYPE_DEFAULT
}

// / 返回参数
type GetVerifyCodeReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VerifyCode     string                 `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	VerifyCodeTime int32                  `protobuf:"varint,4,opt,name=verify_code_time,json=verifyCodeTime,proto3" json:"verify_code_time,omitempty"`
	VerifyCodeLife int32                  `protobuf:"varint,5,opt,name=verify_code_life,json=verifyCodeLife,proto3" json:"verify_code_life,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVerifyCodeReply) Reset() {
	*x = GetVerifyCodeReply{}
	mi := &file_api_verify_v1_verify_code_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVerifyCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVerifyCodeReply) ProtoMessage() {}

func (x *GetVerifyCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_verify_v1_verify_code_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVerifyCodeReply.ProtoReflect.Descriptor instead.
func (*GetVerifyCodeReply) Descriptor() ([]byte, []int) {
	return file_api_verify_v1_verify_code_proto_rawDescGZIP(), []int{1}
}

func (x *GetVerifyCodeReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetVerifyCodeReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetVerifyCodeReply) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *GetVerifyCodeReply) GetVerifyCodeTime() int32 {
	if x != nil {
		return x.VerifyCodeTime
	}
	return 0
}

func (x *GetVerifyCodeReply) GetVerifyCodeLife() int32 {
	if x != nil {
		return x.VerifyCodeLife
	}
	return 0
}

var File_api_verify_v1_verify_code_proto protoreflect.FileDescriptor

const file_api_verify_v1_verify_code_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/verify/v1/verify_code.proto\x12\tverify.v1\"S\n" +
	"\x14GetVerifyCodeRequest\x12\x16\n" +
	"\x06length\x18\x01 \x01(\rR\x06length\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.verify.v1.TYPER\x04type\"\xb7\x01\n" +
	"\x12GetVerifyCodeReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vverify_code\x18\x03 \x01(\tR\n" +
	"verifyCode\x12(\n" +
	"\x10verify_code_time\x18\x04 \x01(\x05R\x0everifyCodeTime\x12(\n" +
	"\x10verify_code_life\x18\x05 \x01(\x05R\x0everifyCodeLife*5\n" +
	"\x04TYPE\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\t\n" +
	"\x05DIGIT\x10\x01\x12\n" +
	"\n" +
	"\x06LETTER\x10\x02\x12\t\n" +
	"\x05MIXED\x10\x032d\n" +
	"\x11VerifyCodeService\x12O\n" +
	"\rGetVerifyCode\x12\x1f.verify.v1.GetVerifyCodeRequest\x1a\x1d.verify.v1.GetVerifyCodeReplyB#Z!go-backend/api/verify/v1;verifypbb\x06proto3"

var (
	file_api_verify_v1_verify_code_proto_rawDescOnce sync.Once
	file_api_verify_v1_verify_code_proto_rawDescData []byte
)

func file_api_verify_v1_verify_code_proto_rawDescGZIP() []byte {
	file_api_verify_v1_verify_code_proto_rawDescOnce.Do(func() {
		file_api_verify_v1_verify_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_verify_v1_verify_code_proto_rawDesc), len(file_api_verify_v1_verify_code_proto_rawDesc)))
	})
	return file_api_verify_v1_verify_code_proto_rawDescData
}

var file_api_verify_v1_verify_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_verify_v1_verify_code_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_verify_v1_verify_code_proto_goTypes = []any{
	(TYPE)(0),                    // 0: verify.v1.TYPE
	(*GetVerifyCodeRequest)(nil), // 1: verify.v1.GetVerifyCodeRequest
	(*GetVerifyCodeReply)(nil),   // 2: verify.v1.GetVerifyCodeReply
}
var file_api_verify_v1_verify_code_proto_depIdxs = []int32{
	0, // 0: verify.v1.GetVerifyCodeRequest.type:type_name -> verify.v1.TYPE
	1, // 1: verify.v1.VerifyCodeService.GetVerifyCode:input_type -> verify.v1.GetVerifyCodeRequest
	2, // 2: verify.v1.VerifyCodeService.GetVerifyCode:output_type -> verify.v1.GetVerifyCodeReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_verify_v1_verify_code_proto_init() }
func file_api_verify_v1_verify_code_proto_init() {
	if File_api_verify_v1_verify_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_verify_v1_verify_code_proto_rawDesc), len(file_api_verify_v1_verify_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_verify_v1_verify_code_proto_goTypes,
		DependencyIndexes: file_api_verify_v1_verify_code_proto_depIdxs,
		EnumInfos:         file_api_verify_v1_verify_code_proto_enumTypes,
		MessageInfos:      file_api_verify_v1_verify_code_proto_msgTypes,
	}.Build()
	File_api_verify_v1_verify_code_proto = out.File
	file_api_verify_v1_verify_code_proto_goTypes = nil
	file_api_verify_v1_verify_code_proto_depIdxs = nil
}
